-- Route color support + public point proposals

alter table if exists public.routes
  add column if not exists route_color text;

create table if not exists public.point_proposals (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  space_type text not null,
  district text not null,
  address text not null,
  lat double precision not null,
  lng double precision not null,
  email text not null,
  photo_url text,
  comment text,
  checklist_json jsonb not null default '{}'::jsonb,
  reviewed boolean not null default false,
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz
);

alter table public.point_proposals enable row level security;

-- Public users can submit proposals.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'point_proposals' and policyname = 'proposals_insert_public'
  ) then
    create policy proposals_insert_public
      on public.point_proposals
      for insert
      to anon, authenticated
      with check (true);
  end if;
end
$$;

-- Only specialists/admins can read proposals.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'point_proposals' and policyname = 'proposals_select_staff'
  ) then
    create policy proposals_select_staff
      on public.point_proposals
      for select
      to authenticated
      using (
        exists (
          select 1
          from public.profiles p
          where p.id = auth.uid() and p.role in ('admin','specialist')
        )
      );
  end if;
end
$$;
